# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VSE

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CancelOrder(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CancelOrder()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCancelOrder(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CancelOrder
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CancelOrder
    def ClientSeq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CancelOrder
    def SymbolId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CancelOrder
    def OrderId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CancelOrderStart(builder):
    builder.StartObject(3)

def Start(builder):
    CancelOrderStart(builder)

def CancelOrderAddClientSeq(builder, clientSeq):
    builder.PrependUint64Slot(0, clientSeq, 0)

def AddClientSeq(builder, clientSeq):
    CancelOrderAddClientSeq(builder, clientSeq)

def CancelOrderAddSymbolId(builder, symbolId):
    builder.PrependUint32Slot(1, symbolId, 0)

def AddSymbolId(builder, symbolId):
    CancelOrderAddSymbolId(builder, symbolId)

def CancelOrderAddOrderId(builder, orderId):
    builder.PrependUint64Slot(2, orderId, 0)

def AddOrderId(builder, orderId):
    CancelOrderAddOrderId(builder, orderId)

def CancelOrderEnd(builder):
    return builder.EndObject()

def End(builder):
    return CancelOrderEnd(builder)
