# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VSE

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExecutionReport(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExecutionReport()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExecutionReport(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExecutionReport
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExecutionReport
    def OrderId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ExecutionReport
    def ClientSeq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ExecutionReport
    def FillPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ExecutionReport
    def FillQty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ExecutionReport
    def Remaining(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ExecutionReport
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ExecutionReport
    def RejectReason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def ExecutionReportStart(builder):
    builder.StartObject(7)

def Start(builder):
    ExecutionReportStart(builder)

def ExecutionReportAddOrderId(builder, orderId):
    builder.PrependUint64Slot(0, orderId, 0)

def AddOrderId(builder, orderId):
    ExecutionReportAddOrderId(builder, orderId)

def ExecutionReportAddClientSeq(builder, clientSeq):
    builder.PrependUint64Slot(1, clientSeq, 0)

def AddClientSeq(builder, clientSeq):
    ExecutionReportAddClientSeq(builder, clientSeq)

def ExecutionReportAddFillPrice(builder, fillPrice):
    builder.PrependInt64Slot(2, fillPrice, 0)

def AddFillPrice(builder, fillPrice):
    ExecutionReportAddFillPrice(builder, fillPrice)

def ExecutionReportAddFillQty(builder, fillQty):
    builder.PrependInt64Slot(3, fillQty, 0)

def AddFillQty(builder, fillQty):
    ExecutionReportAddFillQty(builder, fillQty)

def ExecutionReportAddRemaining(builder, remaining):
    builder.PrependInt64Slot(4, remaining, 0)

def AddRemaining(builder, remaining):
    ExecutionReportAddRemaining(builder, remaining)

def ExecutionReportAddEventType(builder, eventType):
    builder.PrependInt8Slot(5, eventType, 0)

def AddEventType(builder, eventType):
    ExecutionReportAddEventType(builder, eventType)

def ExecutionReportAddRejectReason(builder, rejectReason):
    builder.PrependInt8Slot(6, rejectReason, 0)

def AddRejectReason(builder, rejectReason):
    ExecutionReportAddRejectReason(builder, rejectReason)

def ExecutionReportEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExecutionReportEnd(builder)
