# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VSE

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ModifyOrder(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModifyOrder()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModifyOrder(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ModifyOrder
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModifyOrder
    def ClientSeq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ModifyOrder
    def SymbolId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModifyOrder
    def OrderId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ModifyOrder
    def NewPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModifyOrder
    def NewQty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ModifyOrderStart(builder):
    builder.StartObject(5)

def Start(builder):
    ModifyOrderStart(builder)

def ModifyOrderAddClientSeq(builder, clientSeq):
    builder.PrependUint64Slot(0, clientSeq, 0)

def AddClientSeq(builder, clientSeq):
    ModifyOrderAddClientSeq(builder, clientSeq)

def ModifyOrderAddSymbolId(builder, symbolId):
    builder.PrependUint32Slot(1, symbolId, 0)

def AddSymbolId(builder, symbolId):
    ModifyOrderAddSymbolId(builder, symbolId)

def ModifyOrderAddOrderId(builder, orderId):
    builder.PrependUint64Slot(2, orderId, 0)

def AddOrderId(builder, orderId):
    ModifyOrderAddOrderId(builder, orderId)

def ModifyOrderAddNewPrice(builder, newPrice):
    builder.PrependInt64Slot(3, newPrice, 0)

def AddNewPrice(builder, newPrice):
    ModifyOrderAddNewPrice(builder, newPrice)

def ModifyOrderAddNewQty(builder, newQty):
    builder.PrependUint32Slot(4, newQty, 0)

def AddNewQty(builder, newQty):
    ModifyOrderAddNewQty(builder, newQty)

def ModifyOrderEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModifyOrderEnd(builder)
