# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VSE

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NewOrder(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NewOrder()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNewOrder(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # NewOrder
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NewOrder
    def ClientSeq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # NewOrder
    def SymbolId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # NewOrder
    def Side(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # NewOrder
    def OrderType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # NewOrder
    def Price(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # NewOrder
    def Qty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def NewOrderStart(builder):
    builder.StartObject(6)

def Start(builder):
    NewOrderStart(builder)

def NewOrderAddClientSeq(builder, clientSeq):
    builder.PrependUint64Slot(0, clientSeq, 0)

def AddClientSeq(builder, clientSeq):
    NewOrderAddClientSeq(builder, clientSeq)

def NewOrderAddSymbolId(builder, symbolId):
    builder.PrependUint32Slot(1, symbolId, 0)

def AddSymbolId(builder, symbolId):
    NewOrderAddSymbolId(builder, symbolId)

def NewOrderAddSide(builder, side):
    builder.PrependInt8Slot(2, side, 0)

def AddSide(builder, side):
    NewOrderAddSide(builder, side)

def NewOrderAddOrderType(builder, orderType):
    builder.PrependInt8Slot(3, orderType, 0)

def AddOrderType(builder, orderType):
    NewOrderAddOrderType(builder, orderType)

def NewOrderAddPrice(builder, price):
    builder.PrependInt64Slot(4, price, 0)

def AddPrice(builder, price):
    NewOrderAddPrice(builder, price)

def NewOrderAddQty(builder, qty):
    builder.PrependUint32Slot(5, qty, 0)

def AddQty(builder, qty):
    NewOrderAddQty(builder, qty)

def NewOrderEnd(builder):
    return builder.EndObject()

def End(builder):
    return NewOrderEnd(builder)
