// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WIRETYPES_VSE_H_
#define FLATBUFFERS_GENERATED_WIRETYPES_VSE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace VSE {

struct NewOrder;
struct NewOrderBuilder;

struct CancelOrder;
struct CancelOrderBuilder;

struct ModifyOrder;
struct ModifyOrderBuilder;

struct Request;
struct RequestBuilder;

struct ExecutionReport;
struct ExecutionReportBuilder;

enum Side : int8_t {
  Side_BUY = 0,
  Side_SELL = 1,
  Side_MIN = Side_BUY,
  Side_MAX = Side_SELL
};

inline const Side (&EnumValuesSide())[2] {
  static const Side values[] = {
    Side_BUY,
    Side_SELL
  };
  return values;
}

inline const char * const *EnumNamesSide() {
  static const char * const names[3] = {
    "BUY",
    "SELL",
    nullptr
  };
  return names;
}

inline const char *EnumNameSide(Side e) {
  if (::flatbuffers::IsOutRange(e, Side_BUY, Side_SELL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSide()[index];
}

enum OrderType : int8_t {
  OrderType_LIMIT = 0,
  OrderType_MARKET = 1,
  OrderType_MIN = OrderType_LIMIT,
  OrderType_MAX = OrderType_MARKET
};

inline const OrderType (&EnumValuesOrderType())[2] {
  static const OrderType values[] = {
    OrderType_LIMIT,
    OrderType_MARKET
  };
  return values;
}

inline const char * const *EnumNamesOrderType() {
  static const char * const names[3] = {
    "LIMIT",
    "MARKET",
    nullptr
  };
  return names;
}

inline const char *EnumNameOrderType(OrderType e) {
  if (::flatbuffers::IsOutRange(e, OrderType_LIMIT, OrderType_MARKET)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOrderType()[index];
}

enum RequestBody : uint8_t {
  RequestBody_NONE = 0,
  RequestBody_NewOrder = 1,
  RequestBody_CancelOrder = 2,
  RequestBody_ModifyOrder = 3,
  RequestBody_MIN = RequestBody_NONE,
  RequestBody_MAX = RequestBody_ModifyOrder
};

inline const RequestBody (&EnumValuesRequestBody())[4] {
  static const RequestBody values[] = {
    RequestBody_NONE,
    RequestBody_NewOrder,
    RequestBody_CancelOrder,
    RequestBody_ModifyOrder
  };
  return values;
}

inline const char * const *EnumNamesRequestBody() {
  static const char * const names[5] = {
    "NONE",
    "NewOrder",
    "CancelOrder",
    "ModifyOrder",
    nullptr
  };
  return names;
}

inline const char *EnumNameRequestBody(RequestBody e) {
  if (::flatbuffers::IsOutRange(e, RequestBody_NONE, RequestBody_ModifyOrder)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRequestBody()[index];
}

template<typename T> struct RequestBodyTraits {
  static const RequestBody enum_value = RequestBody_NONE;
};

template<> struct RequestBodyTraits<VSE::NewOrder> {
  static const RequestBody enum_value = RequestBody_NewOrder;
};

template<> struct RequestBodyTraits<VSE::CancelOrder> {
  static const RequestBody enum_value = RequestBody_CancelOrder;
};

template<> struct RequestBodyTraits<VSE::ModifyOrder> {
  static const RequestBody enum_value = RequestBody_ModifyOrder;
};

bool VerifyRequestBody(::flatbuffers::Verifier &verifier, const void *obj, RequestBody type);
bool VerifyRequestBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct NewOrder FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NewOrderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_SEQ = 4,
    VT_SYMBOL_ID = 6,
    VT_SIDE = 8,
    VT_ORDER_TYPE = 10,
    VT_PRICE = 12,
    VT_QTY = 14
  };
  uint64_t client_seq() const {
    return GetField<uint64_t>(VT_CLIENT_SEQ, 0);
  }
  uint32_t symbol_id() const {
    return GetField<uint32_t>(VT_SYMBOL_ID, 0);
  }
  VSE::Side side() const {
    return static_cast<VSE::Side>(GetField<int8_t>(VT_SIDE, 0));
  }
  VSE::OrderType order_type() const {
    return static_cast<VSE::OrderType>(GetField<int8_t>(VT_ORDER_TYPE, 0));
  }
  int64_t price() const {
    return GetField<int64_t>(VT_PRICE, 0);
  }
  uint32_t qty() const {
    return GetField<uint32_t>(VT_QTY, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_SEQ, 8) &&
           VerifyField<uint32_t>(verifier, VT_SYMBOL_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_SIDE, 1) &&
           VerifyField<int8_t>(verifier, VT_ORDER_TYPE, 1) &&
           VerifyField<int64_t>(verifier, VT_PRICE, 8) &&
           VerifyField<uint32_t>(verifier, VT_QTY, 4) &&
           verifier.EndTable();
  }
};

struct NewOrderBuilder {
  typedef NewOrder Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_seq(uint64_t client_seq) {
    fbb_.AddElement<uint64_t>(NewOrder::VT_CLIENT_SEQ, client_seq, 0);
  }
  void add_symbol_id(uint32_t symbol_id) {
    fbb_.AddElement<uint32_t>(NewOrder::VT_SYMBOL_ID, symbol_id, 0);
  }
  void add_side(VSE::Side side) {
    fbb_.AddElement<int8_t>(NewOrder::VT_SIDE, static_cast<int8_t>(side), 0);
  }
  void add_order_type(VSE::OrderType order_type) {
    fbb_.AddElement<int8_t>(NewOrder::VT_ORDER_TYPE, static_cast<int8_t>(order_type), 0);
  }
  void add_price(int64_t price) {
    fbb_.AddElement<int64_t>(NewOrder::VT_PRICE, price, 0);
  }
  void add_qty(uint32_t qty) {
    fbb_.AddElement<uint32_t>(NewOrder::VT_QTY, qty, 0);
  }
  explicit NewOrderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NewOrder> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NewOrder>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NewOrder> CreateNewOrder(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_seq = 0,
    uint32_t symbol_id = 0,
    VSE::Side side = VSE::Side_BUY,
    VSE::OrderType order_type = VSE::OrderType_LIMIT,
    int64_t price = 0,
    uint32_t qty = 0) {
  NewOrderBuilder builder_(_fbb);
  builder_.add_price(price);
  builder_.add_client_seq(client_seq);
  builder_.add_qty(qty);
  builder_.add_symbol_id(symbol_id);
  builder_.add_order_type(order_type);
  builder_.add_side(side);
  return builder_.Finish();
}

struct CancelOrder FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CancelOrderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_SEQ = 4,
    VT_SYMBOL_ID = 6,
    VT_ORDER_ID = 8
  };
  uint64_t client_seq() const {
    return GetField<uint64_t>(VT_CLIENT_SEQ, 0);
  }
  uint32_t symbol_id() const {
    return GetField<uint32_t>(VT_SYMBOL_ID, 0);
  }
  uint64_t order_id() const {
    return GetField<uint64_t>(VT_ORDER_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_SEQ, 8) &&
           VerifyField<uint32_t>(verifier, VT_SYMBOL_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_ORDER_ID, 8) &&
           verifier.EndTable();
  }
};

struct CancelOrderBuilder {
  typedef CancelOrder Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_seq(uint64_t client_seq) {
    fbb_.AddElement<uint64_t>(CancelOrder::VT_CLIENT_SEQ, client_seq, 0);
  }
  void add_symbol_id(uint32_t symbol_id) {
    fbb_.AddElement<uint32_t>(CancelOrder::VT_SYMBOL_ID, symbol_id, 0);
  }
  void add_order_id(uint64_t order_id) {
    fbb_.AddElement<uint64_t>(CancelOrder::VT_ORDER_ID, order_id, 0);
  }
  explicit CancelOrderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CancelOrder> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CancelOrder>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CancelOrder> CreateCancelOrder(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_seq = 0,
    uint32_t symbol_id = 0,
    uint64_t order_id = 0) {
  CancelOrderBuilder builder_(_fbb);
  builder_.add_order_id(order_id);
  builder_.add_client_seq(client_seq);
  builder_.add_symbol_id(symbol_id);
  return builder_.Finish();
}

struct ModifyOrder FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModifyOrderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_SEQ = 4,
    VT_SYMBOL_ID = 6,
    VT_ORDER_ID = 8,
    VT_NEW_PRICE = 10,
    VT_NEW_QTY = 12
  };
  uint64_t client_seq() const {
    return GetField<uint64_t>(VT_CLIENT_SEQ, 0);
  }
  uint32_t symbol_id() const {
    return GetField<uint32_t>(VT_SYMBOL_ID, 0);
  }
  uint64_t order_id() const {
    return GetField<uint64_t>(VT_ORDER_ID, 0);
  }
  int64_t new_price() const {
    return GetField<int64_t>(VT_NEW_PRICE, 0);
  }
  uint32_t new_qty() const {
    return GetField<uint32_t>(VT_NEW_QTY, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_SEQ, 8) &&
           VerifyField<uint32_t>(verifier, VT_SYMBOL_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_ORDER_ID, 8) &&
           VerifyField<int64_t>(verifier, VT_NEW_PRICE, 8) &&
           VerifyField<uint32_t>(verifier, VT_NEW_QTY, 4) &&
           verifier.EndTable();
  }
};

struct ModifyOrderBuilder {
  typedef ModifyOrder Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_seq(uint64_t client_seq) {
    fbb_.AddElement<uint64_t>(ModifyOrder::VT_CLIENT_SEQ, client_seq, 0);
  }
  void add_symbol_id(uint32_t symbol_id) {
    fbb_.AddElement<uint32_t>(ModifyOrder::VT_SYMBOL_ID, symbol_id, 0);
  }
  void add_order_id(uint64_t order_id) {
    fbb_.AddElement<uint64_t>(ModifyOrder::VT_ORDER_ID, order_id, 0);
  }
  void add_new_price(int64_t new_price) {
    fbb_.AddElement<int64_t>(ModifyOrder::VT_NEW_PRICE, new_price, 0);
  }
  void add_new_qty(uint32_t new_qty) {
    fbb_.AddElement<uint32_t>(ModifyOrder::VT_NEW_QTY, new_qty, 0);
  }
  explicit ModifyOrderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModifyOrder> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModifyOrder>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModifyOrder> CreateModifyOrder(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_seq = 0,
    uint32_t symbol_id = 0,
    uint64_t order_id = 0,
    int64_t new_price = 0,
    uint32_t new_qty = 0) {
  ModifyOrderBuilder builder_(_fbb);
  builder_.add_new_price(new_price);
  builder_.add_order_id(order_id);
  builder_.add_client_seq(client_seq);
  builder_.add_new_qty(new_qty);
  builder_.add_symbol_id(symbol_id);
  return builder_.Finish();
}

struct Request FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_TYPE = 4,
    VT_BODY = 6
  };
  VSE::RequestBody body_type() const {
    return static_cast<VSE::RequestBody>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const VSE::NewOrder *body_as_NewOrder() const {
    return body_type() == VSE::RequestBody_NewOrder ? static_cast<const VSE::NewOrder *>(body()) : nullptr;
  }
  const VSE::CancelOrder *body_as_CancelOrder() const {
    return body_type() == VSE::RequestBody_CancelOrder ? static_cast<const VSE::CancelOrder *>(body()) : nullptr;
  }
  const VSE::ModifyOrder *body_as_ModifyOrder() const {
    return body_type() == VSE::RequestBody_ModifyOrder ? static_cast<const VSE::ModifyOrder *>(body()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE, 1) &&
           VerifyOffset(verifier, VT_BODY) &&
           VerifyRequestBody(verifier, body(), body_type()) &&
           verifier.EndTable();
  }
};

template<> inline const VSE::NewOrder *Request::body_as<VSE::NewOrder>() const {
  return body_as_NewOrder();
}

template<> inline const VSE::CancelOrder *Request::body_as<VSE::CancelOrder>() const {
  return body_as_CancelOrder();
}

template<> inline const VSE::ModifyOrder *Request::body_as<VSE::ModifyOrder>() const {
  return body_as_ModifyOrder();
}

struct RequestBuilder {
  typedef Request Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body_type(VSE::RequestBody body_type) {
    fbb_.AddElement<uint8_t>(Request::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(::flatbuffers::Offset<void> body) {
    fbb_.AddOffset(Request::VT_BODY, body);
  }
  explicit RequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Request> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Request>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Request> CreateRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    VSE::RequestBody body_type = VSE::RequestBody_NONE,
    ::flatbuffers::Offset<void> body = 0) {
  RequestBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_body_type(body_type);
  return builder_.Finish();
}

struct ExecutionReport FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ExecutionReportBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ORDER_ID = 4,
    VT_CLIENT_SEQ = 6,
    VT_FILL_PRICE = 8,
    VT_FILL_QTY = 10,
    VT_REMAINING = 12,
    VT_EVENT_TYPE = 14,
    VT_REJECT_REASON = 16
  };
  uint64_t order_id() const {
    return GetField<uint64_t>(VT_ORDER_ID, 0);
  }
  uint64_t client_seq() const {
    return GetField<uint64_t>(VT_CLIENT_SEQ, 0);
  }
  int64_t fill_price() const {
    return GetField<int64_t>(VT_FILL_PRICE, 0);
  }
  int64_t fill_qty() const {
    return GetField<int64_t>(VT_FILL_QTY, 0);
  }
  int64_t remaining() const {
    return GetField<int64_t>(VT_REMAINING, 0);
  }
  int8_t event_type() const {
    return GetField<int8_t>(VT_EVENT_TYPE, 0);
  }
  int8_t reject_reason() const {
    return GetField<int8_t>(VT_REJECT_REASON, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ORDER_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_SEQ, 8) &&
           VerifyField<int64_t>(verifier, VT_FILL_PRICE, 8) &&
           VerifyField<int64_t>(verifier, VT_FILL_QTY, 8) &&
           VerifyField<int64_t>(verifier, VT_REMAINING, 8) &&
           VerifyField<int8_t>(verifier, VT_EVENT_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_REJECT_REASON, 1) &&
           verifier.EndTable();
  }
};

struct ExecutionReportBuilder {
  typedef ExecutionReport Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_order_id(uint64_t order_id) {
    fbb_.AddElement<uint64_t>(ExecutionReport::VT_ORDER_ID, order_id, 0);
  }
  void add_client_seq(uint64_t client_seq) {
    fbb_.AddElement<uint64_t>(ExecutionReport::VT_CLIENT_SEQ, client_seq, 0);
  }
  void add_fill_price(int64_t fill_price) {
    fbb_.AddElement<int64_t>(ExecutionReport::VT_FILL_PRICE, fill_price, 0);
  }
  void add_fill_qty(int64_t fill_qty) {
    fbb_.AddElement<int64_t>(ExecutionReport::VT_FILL_QTY, fill_qty, 0);
  }
  void add_remaining(int64_t remaining) {
    fbb_.AddElement<int64_t>(ExecutionReport::VT_REMAINING, remaining, 0);
  }
  void add_event_type(int8_t event_type) {
    fbb_.AddElement<int8_t>(ExecutionReport::VT_EVENT_TYPE, event_type, 0);
  }
  void add_reject_reason(int8_t reject_reason) {
    fbb_.AddElement<int8_t>(ExecutionReport::VT_REJECT_REASON, reject_reason, 0);
  }
  explicit ExecutionReportBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ExecutionReport> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ExecutionReport>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ExecutionReport> CreateExecutionReport(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t order_id = 0,
    uint64_t client_seq = 0,
    int64_t fill_price = 0,
    int64_t fill_qty = 0,
    int64_t remaining = 0,
    int8_t event_type = 0,
    int8_t reject_reason = 0) {
  ExecutionReportBuilder builder_(_fbb);
  builder_.add_remaining(remaining);
  builder_.add_fill_qty(fill_qty);
  builder_.add_fill_price(fill_price);
  builder_.add_client_seq(client_seq);
  builder_.add_order_id(order_id);
  builder_.add_reject_reason(reject_reason);
  builder_.add_event_type(event_type);
  return builder_.Finish();
}

inline bool VerifyRequestBody(::flatbuffers::Verifier &verifier, const void *obj, RequestBody type) {
  switch (type) {
    case RequestBody_NONE: {
      return true;
    }
    case RequestBody_NewOrder: {
      auto ptr = reinterpret_cast<const VSE::NewOrder *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RequestBody_CancelOrder: {
      auto ptr = reinterpret_cast<const VSE::CancelOrder *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RequestBody_ModifyOrder: {
      auto ptr = reinterpret_cast<const VSE::ModifyOrder *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyRequestBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyRequestBody(
        verifier,  values->Get(i), types->GetEnum<RequestBody>(i))) {
      return false;
    }
  }
  return true;
}

inline const VSE::Request *GetRequest(const void *buf) {
  return ::flatbuffers::GetRoot<VSE::Request>(buf);
}

inline const VSE::Request *GetSizePrefixedRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<VSE::Request>(buf);
}

inline bool VerifyRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<VSE::Request>(nullptr);
}

inline bool VerifySizePrefixedRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<VSE::Request>(nullptr);
}

inline void FinishRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSE::Request> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSE::Request> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace VSE

#endif  // FLATBUFFERS_GENERATED_WIRETYPES_VSE_H_
